# Generated by Django 5.0.3 on 2024-03-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_buisness"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_buisness",
            new_name="is_business",
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.CharField(default="C", max_length=10),
        ),
    ]
